### PR TITLE
Use Controller.Challenge \ Controller.Forbid

### LINKED ISSUE #294: Use Controller.Challenge \ Controller.Forbid
Follow up to https://github.com/aspnet/Mvc/issues/3242

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #294

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by rustd** [comment]
:shipit:

**Comment by rustd** [comment]
cc @joeloff Only merge this when there is a successful coherence signed build for dev

**Comment by joeloff** [comment]
@rustd Unless someone checks something into one of the Dev branches, Coherence won't trigger, or did you want me to force a build?. Are we waiting for something specific?

**Comment by rustd** [comment]
This PR depends on the following change in MVC https://github.com/aspnet/Mvc/issues/3242 which was made for RC2

**Comment by Eilon** [comment]
:shipit:

**Comment by davidfowl** [comment]
:shipit:

**Pull request closed without merging**
