### PR TITLE
Remove Project_ReadMe.txt from templates

### PR DESCRIPTION
**Pull request by phenning**
@mlorbe, @joeloff  when we get the getting started changes in

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@phenning Phil, is there something that can be used as replacement for these files? I've used automated script to generated markdown version of them for other projects. Thanks!

**Comment by phenning** [comment]
@peterblazejewicz ,  @sayedihashimi had some ideas for this. He will follow up with you.

**Comment by peterblazejewicz** [comment]
ACK. Thanks!

**Comment by sayedihashimi** [comment]
Hi @peterblazejewicz. We are working on a feature in VS where we can have an "interactive" Project Overview page. On this page users will see links to websites, as well as links which invoke specific actions in VS. For `yo aspnet` I think we can take the Overview Page for ASP.NET Core/.NET Core and create .md files with similar content. We can replace the interactive links to doc links. Thoughts?

We are still finalizing the overview content so I'm thinking that we can address the readme for `yo aspnet` in a week or so.

**Comment by peterblazejewicz** [comment]
@sayedihashimi Yes, I remember this (I've seen a demo). That's a broader then `yo aspnet`. I'd rather first make sure that `dotnet cli` folks also follow the change:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-new/CSharp_Web/Project_Readme.html so you have consistent user experience with tooling.

**Comment by sayedihashimi** [comment]
@peterblazejewicz yes we will need to add a file for `dotnet new`.

@phenning I think we forgot about that :)

**Comment by peterblazejewicz** [comment]
You are welcome :)

**Pull request merged**
