### PR TITLE
Update .NET Core templates

### PR DESCRIPTION
**Pull request by rchande**
Use netstandard TFMs
Update to most recent package build, which allows exclusion of imports statements.

### CODE REVIEW

**Comment by rchande** [comment]
Please review @ericstj @cartermp @phenning

**Comment by Pilchie** [comment]
:+1: from me.

**Comment by cartermp** [comment]
LGTM

**Comment by ericstj** [comment]
23830 packages aren't published yet, won't that be a problem?  Also, have you coordinated with @jhendrixMSFT to make sure you use the same package versions are inserted into VS.

**Comment by ericstj** [comment]
And actually the package versions would be 23901 since the month changed.

**Pull request merged**
