### PR TITLE
Addresses #184 remove repeated `btn-default` class

### PR DESCRIPTION
**Pull request by spboyer**
- Addresses #184 
- removes repeated `btn-default` class from StarterWeb template

### CODE REVIEW

**Comment by rustd** [comment]
:shipit: @phenning This should be good to be merged.

**Comment by scottaddie** [comment]
@spboyer Thanks for fixing this. It was driving me nuts!

**Comment by sayedihashimi** [comment]
Thanks @spboyer, happy to see you here :)

**Comment by spboyer** [comment]
thanks @sayedihashimi - i wish my commits actually showed in the commits list...

**Comment by sayedihashimi** [comment]
@spboyer why isn't your name showing up?

**Comment by sayedihashimi** [comment]
If it hasn't merged to master maybe thats why?

**Comment by spboyer** [comment]
Not sure. @peterblazejewicz did this one https://github.com/aspnet/Templates/pull/215 was merged to dev and shows as commit? Just weird.

**Comment by phenning** [comment]
I see it.  The commit was on October 12th, so it is farther down the list

remove repeated `btn-default` class 
Shayne Boyer authored 4 days ago 

Your Signal-R commit is also showing.

**Pull request merged**
