### PR TITLE
Remove web command profile from WebAPI launchSetting.json

### LINKED ISSUE #432: Remove web command profile from WebAPI launchSetting.json
The profile is no longer created in the tooling, so it should be removed

### PR DESCRIPTION
**Pull request by phenning**
Fixes #432 

@rustd 
@BillHiebert 

Since we no longer have a web profile by default, we should remove this from the template.

### CODE REVIEW

**Comment by rustd** [comment]
Probably. It was brought up in the templates review that Bill was working on the replacement for this. /cc @sayedihashimi

**Comment by phenning** [comment]
We should still remove it until we have the replacement, since we only have it for WebAPI Windows auth only (not there for non-auth)

**Comment by rustd** [comment]
Yes, we would remove it and replace it with what Bill is working on

**Comment by phenning** [comment]
OK, I'll merge this change and add the new version back in a later commit, after that work is done.

**Pull request merged**
