### PR TITLE
Update the Startup.cs to have a placeholder for external auth

### LINKED ISSUE #540: Update the Startup.cs to have a placeholder for external auth
Right now the Startup.cs has a line like this:

``` csharp
// To configure external authentication please see http://go.microsoft.com/fwlink/?LinkID=532715
```

It's not clear that the middleware configuration should go there, and not elsewhere in the file. This isn't helped by the docs not being super clear (https://github.com/aspnet/Docs/issues/1187) but our templates could improve this as well but indicating that external auth middleware should go there.

``` csharp
// To configure external authentication please see http://go.microsoft.com/fwlink/?LinkID=532715
// Place external authentication middleware configuration here
```

### PR DESCRIPTION
**Pull request by phenning**
Fixes #540 
//cc @anurse @rustd

### CODE REVIEW

**Comment by rustd** [comment]
:shipit:

**Comment by phenning** [comment]
merged

**Comment by peterblazejewicz** [comment]
@phenning Do you mean `merged` or `closed`?

**Comment by phenning** [comment]
Was merged manually, not showing up in UI

**Pull request closed without merging**
