### PR TITLE
Rename UseIIS to UseIISIntegration. Add new UseKestrel.

### PR DESCRIPTION
**Pull request by Tratcher**
@phenning @rustd @JunTaoLuo

### CODE REVIEW

**Comment by phenning** [comment]
Looks good, please wait until we have a coherence signed in release with these changes before merging

**Comment by rustd** [comment]
@phenning @Tratcher do we have a coherence-signed build with these changes? If not then we should revert this merge until we have one otherwise templates will be broken.

**Comment by Tratcher** [comment]
Yes it's already available on coherence-signed. This isn't causing any build failures is it?

**Comment by phenning** [comment]
We have an updated build with them in release.

On Apr 11, 2016, at 3:14 PM, Pranav Rastogi <notifications@github.com<mailto:notifications@github.com>> wrote:

@phenninghttps://github.com/phenning @Tratcherhttps://github.com/Tratcher do we have a coherence-signed build with these changes? If not then we should revert this merge until we have one otherwise templates will be broken.

##

**Comment by phenning** [comment]
Nope, everything is working as expected.

On Apr 11, 2016, at 3:20 PM, Chris R <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes it's already available on coherence-signed. This isn't causing any build failures is it?

##

**Pull request merged**
