### PR TITLE
Use IsSignedIn() instead of existing api in _LoginPartial.cshtml

### LINKED ISSUE #56: Use IsSignedIn() instead of existing api in _LoginPartial.cshtml
Had a chat with @HaoK  and in the existing _LoginPartial.cshtml file the way we check if user is logged in is using `User.Identity.Authenticated`. It should be updated to use `User.IsSignedIn()`

### PR DESCRIPTION
**Pull request by phenning**
Fixes #56 

Also updated the controllers. Individual auth controller was already using the proper API.

@HaoK @rustd

### CODE REVIEW

**Comment by rustd** [comment]
let's make this change only for Individual Auth template. Not sure if this works with Org Auth. @HaoK do you know?

**Comment by HaoK** [comment]
I would try the changes before you check them in yes :)

**Comment by phenning** [comment]
Updated the PR, only doing individual auth now, we're not pulling in the package that has the extension in the template, so minimizing this change for now.

**Comment by phenning** [comment]
Merged to dev

**Pull request closed without merging**
