### PR TITLE
Remove comment about nuget packages

### PR DESCRIPTION
**Pull request by rchande**
@phenning Can you merge/let me know if this is the right branch?
cc @sayedihashimi @Pilchie

### CODE REVIEW

**Comment by phenning** [comment]
Correct branch, merging!

**Comment by Pilchie** [comment]
This needs to be inserted somewhere, right?  @phenning - will that be taken care of automatically, or does @rchande need to do it?

**Comment by phenning** [comment]
Nope, we'll take care of inserting the package as soon as we get a template build. It should go in today.

**Comment by Pilchie** [comment]
Thanks!

**Pull request merged**
