### PR TITLE
Web API: Windows Auth Template

### LINKED ISSUE #202: Web API: Windows Auth Template

### PR DESCRIPTION
**Pull request by phenning**
Closes #202 

@rustd, @joeloff

### CODE REVIEW

**Comment by brockallen** [comment]
I don't really see the contents of the template, so is this a browser-based template? If so I wanted to ask if the template include XSRF protections (since it says you're using Windows Auth).

**Comment by phenning** [comment]
This template has no UI, we just need to update the launchSettings to enable windows auth and disable anonymous.

This follows the same pattern as StarterWeb Windows auth, only that template is a UI template so it also updates the _Layout.cshtml.

**Comment by brockallen** [comment]
Ok... so then perhaps a comment about XSRF protection on Web APIs might be useful (especially when using an implicit authentication mechanism like windows authN).

**Comment by phenning** [comment]
@rustd 

Should we provide a ValuesController for all auth types with:
1. [Authorize] set at the class level.
2. Add a comment in Post, Put and Delete:

// For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see [fwlink].

**Comment by rustd** [comment]
@phenning let's do it. My sample had a ValuesController as well.
/cc @danroth27

**Comment by brockallen** [comment]
I suspect the link you will be providing should be docs from none other than @blowdart. :trollface:

**Comment by phenning** [comment]
Updated the PR.

**Comment by rustd** [comment]
:shipit:

**Pull request merged**
