### PR TITLE
Fix typo wrong methode FindByNameAsync=>FindByEmailAsync

### PR DESCRIPTION
**Pull request by Anderman**
@rustd I found that the wrong method was use for finding an email address

### CODE REVIEW

**Comment by rustd** [comment]
FindByName is fine since in the templates email is used as a name as well.

**Comment by Anderman** [comment]
(-; Yep that's is true. I found this after changing the webapp. I think I will not be the last one.

**Comment by Anderman** [comment]
@rustd Okee there are indeed more places that require that username is the same as email address.

```
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
```

PasswordSignInAsync require a username. 

Next time I will first create an issue before sending a PR

**Comment by rustd** [comment]
@Anderman no worries. I am closing this PR.

**Pull request closed without merging**
