### PR TITLE
:arrow_up: Update client side dependencies. Closes #348

### LINKED ISSUE #348: Update JS and CSS libraries to latest available version

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit updates Bower managed dependencies
- Bootstrap 3.3.6
- jQuery.Validation.Unobtrusive 3.2.5

The updated content does not include non-essential content usually
shipped with Bower - so the commit just updates existing content to
higher version.
The exceptions are source maps are added to Bootstrap distribution
- as they come with default distribution and are crucial for development - when the CDN fallback fires the minimized version of libraries are used

The commit also updates CDN Bootstrap version to 3.3.6

The commit cannot yet update jQuery Validation Unobtrusive CDN due to this:
https://github.com/aspnet/Templates/issues/353
https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Views/Shared/_ValidationScriptsPartial.cshtml#L10

Thanks!

Changed files:
src/BaseTemplates/StarterWeb/Views/Shared/_Layout.cshtml
src/BaseTemplates/StarterWeb/bower.json
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/.bower.json
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css.map
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css.map
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap.css
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap.css.map
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.js
src/BaseTemplates/StarterWeb/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
src/BaseTemplates/StarterWeb/wwwroot/lib/jquery-validation-unobtrusive/.bower.json
src/Rules/StarterWeb/AI/CommonAuth/Views/Shared/_Layout.cshtml
src/Rules/StarterWeb/AI/NoAuth/Views/Shared/_Layout.cshtml
src/Rules/StarterWeb/AI/WindowsAuth/Views/Shared/_Layout.cshtml
src/Rules/StarterWeb/CommonAuth/Views/Shared/_Layout.cshtml
src/Rules/StarterWeb/WindowsAuth/Views/Shared/_Layout.cshtml

### CODE REVIEW

**Comment by phenning** [comment]
@rustd, are we good to take this after review?

**Comment by rustd** [comment]
Not yet. We need to confirm the version of the OSS packages.

**Comment by sayedihashimi** [comment]
@rustd what's the status here?

**Comment by phenning** [comment]
Closing this one, we have another PR that also contained jQuery update, but not the unobtrusive package.  That's what we want for now.

**Pull request closed without merging**
