### PR TITLE
Corrects the usage of GC Server configuration within project.JSON

### LINKED ISSUE #575: Server GC
See https://github.com/aspnet/Docs/issues/1237

In the templates we have

``` json
"runtimeOptions": {
    "gcServer": true
}
```

It should be 

``` json
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
```

cc @danroth27

### PR DESCRIPTION
**Pull request by JamieKeeling**
Resolves #575 by updating the relevant project templates to correctly specify GC behaviour.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@phenning

**Comment by phenning** [comment]
Holding off merging this for now, until we can determine proper branch.

**Comment by JamieKeeling** [comment]
@phenning Is there anything you need from me to help?

**Comment by phenning** [comment]
@JamieKeeling I'll handle rebasing and merging back to dev. Thanks for the offer though

**Comment by phenning** [comment]
Merged to release branch

**Pull request closed without merging**
