### PR TITLE
Update HomeController.cs

### PR DESCRIPTION
**Pull request by yukozh**

### CODE REVIEW

**Comment by rustd** [comment]
:shipit: @phenning this can be merged.

**Comment by phenning** [comment]
if you are going to update it here, can you also update it here?

Rules\StarterWeb\OrganizationalAuth\Common\Controllers\HomeController.cs

**Comment by peterblazejewicz** [comment]
Q: Which view will be rendered when Error middleware fires /Home/Error action?

**Comment by yukozh** [comment]
@peterblazejewicz This is the razor view engine problem. it is able to find error.cshtml automaticly. you can see the source in mvc repo. /Home/Error is related on routing, not view engine. Here, it is just a rule for searching view. We can also use default rule to find it. So, I created this PR.

**Comment by yukozh** [comment]
thanks a lot.

**Comment by peterblazejewicz** [comment]
@Kagamine Thanks!

**Pull request merged**
