### PR TITLE
Use new to create DbContext for running Migrate

### PR DESCRIPTION
**Pull request by ajcvickers**
This is an optional change. The code already there should still work, but this ia a new option that is available because of the EF D.I. changes.

### CODE REVIEW

**Comment by ajcvickers** [comment]
cc @divega @rowanmiller

**Comment by rustd** [comment]
ping @divega @rowanmiller Do you want to take this change in for RC2? if so please review this and let us know if this change is good.

**Comment by rowanmiller** [comment]
I think we should take it. :shipit: from my perspective.

**Comment by rustd** [comment]
Thanks! @phenning this should be good to be merged with next coherence signed build.

**Comment by rowanmiller** [comment]
Do you want someone on the EF team to merge this?

**Comment by rustd** [comment]
No. @phenning can merge this. Do we need any new EF runtime bits for this change?

**Comment by ajcvickers** [comment]
@rustd @phenning No new EF needed.

**Comment by rustd** [comment]
Thanks! @phenning this is good to be merged now.

**Comment by rowanmiller** [comment]
@rustd this is the PR we discussed in template review that hasn't made it into release/dev branches

**Comment by phenning** [comment]
Interesting this got merged into some weird branch.. I'll merge it into release/dev now

**Comment by phenning** [comment]
Merged this properly now to release

**Pull request merged**
