### PR TITLE
Templates to enforce `using`

### PR DESCRIPTION
**Pull request by IEvangelist**
Since the `IWebHost` implements `IDisposable`, let's make the templates enforce best practices.

### CODE REVIEW

**Comment by phenning** [comment]
@davidfowl thoughts?

**Comment by peterblazejewicz** [comment]
2c: The best practise documentation (and sample code) usually are simple, short and explicit:
https://msdn.microsoft.com/en-us/library/3bwa4xa9(v=vs.110).aspx
e.g.:

``` csharp
using (StreamReader s = new StreamReader("File1.txt")) {
```

but not:

```
using(var a = new b()
  .UseFeatureC()
  .UseFeatureD()
  .UseAsFeatureE()
  .Build())
```

In such complex code there is no obvious hint which method returns IDisposable: contructor, extension methods, build method? It obviates possible gain from changing a code IMO.
The linked docs states that there are **two** ways to handle IDisposable BTW (depending on contex, preferences, etc)

@IEvangelist white space should not to be changed, see: https://github.com/aspnet/Templates/pull/639/files?w=1
@phenning https://github.com/aspnet/Templates/issues/226

**Comment by IEvangelist** [comment]
@peterblazejewicz So would you prefer to have a `try / finally`? I guess my point is that I want the `IDisposable` to be honored. It belongs in either a `using` or in a `try / finally`.

**Comment by peterblazejewicz** [comment]
No, I don't have preferences here (I use a lot of `using` at work though). Let's wait for @davidfowl 💬

**Comment by davidfowl** [comment]
We debated this a bit and moved away from it. Run disposed the appropriate things.

**Comment by IEvangelist** [comment]
@davidfowl I see why now. It certainly is **not** obvious from the templates -- you have to go looking at [the implementation of `Run`](https://github.com/aspnet/Hosting/blob/7b513de5c3a8379706a76c6b7bb0380ee83194b7/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs), which is an extension method, which internally wraps its usage in a `using`.

**Comment by davidfowl** [comment]
Yep! It's a bit cleaner to look at since wrapping that many lines of code in a using is pretty awful.

**Pull request closed without merging**
