### PR TITLE
Remove AssemblyInfo.cs from templates

### LINKED ISSUE #263: Remove AssemblyInfo.cs
It is considered more of an edge case to use the AssemblyInfo.cs in an ASP.NET 5 project

### PR DESCRIPTION
**Pull request by phenning**
Fixes #263
/cc @rustd @madskristensen @davidfowl

### CODE REVIEW

**Comment by madskristensen** [comment]
It should only be removed for the web templates and not for class libraries and console apps. Sorry for not being more clear

**Comment by phenning** [comment]
@madskristensen Updated PR, adding it back for class, console,

**Comment by madskristensen** [comment]
Looks good to me :+1:

**Comment by phenning** [comment]
Merged

**Pull request closed without merging**
