### PR TITLE
React to rename Framework to Extensions

### PR DESCRIPTION
**Pull request by Anderman**
Fix makefile.shade to run dnx command

@rustd I fixed some now the test will be run at the end of the build.cmd

### CODE REVIEW

**Comment by rustd** [comment]
@phenning thoughts?

**Comment by phenning** [comment]
Taking a look at this today, thanks!

**Comment by phenning** [comment]
@Anderman 

This PR only partially fixes the issue with unit tests, I'm still getting failures locally. I'll continue investigating and will likely cherry-pick some of these commits when the final fix comes in.

**Comment by Anderman** [comment]
Oke, the last time i did the the test I had some problems with Components that did not work anymore in the developement branch. like browserlink or insigth, And an issue with the validation attribute helper.

**Comment by phenning** [comment]
Closing this as it is rather stale now.

**Pull request closed without merging**
